language: rust
rust:
- nightly
- stable

branches:
  only:
    - staging
    - trying
    - master

script:
- cargo build --verbose
- cargo test --verbose
- cargo build --verbose --no-default-features
- cargo test --verbose --no-default-features
- cargo build --verbose --features serialize
- cargo test --verbose --features serialize
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo bench --verbose --no-run;
  fi

after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  mkdir tmp &&
  cd tmp &&
  git clone https://github.com/slide-rs/specs-website &&
  cd specs-website &&
  ./scripts/install.sh &&
  ./scripts/gen.sh &&
  ./scripts/commit.sh &&
  git config --global user.email "torkleyy@gmail.com" &&
  git config --global user.name "Website updater" &&
  git push -fq https://${GH_TOKEN}@github.com/slide-rs/specs-website.git gh-pages

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cdff2f522a8c4588a82a
    on_success: always
    on_failure: always
    on_start: never
