language: rust
rust:
- nightly
- stable

cache:
  cargo: true

branches:
  only:
    - staging
    - trying
    - master

before_script:
- export PATH="$PATH:$HOME/.cargo/bin"

script:
- cargo build --features="common,serde,rudy" --verbose
- cargo test --features="common,serde,rudy" --verbose
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo build --all-features --verbose;
    cargo test --all-features --verbose;
    cargo bench --verbose --no-run --all-features;
  fi
- cargo build --manifest-path ./specs-derive/Cargo.toml --verbose
- cargo test --manifest-path ./specs-derive/Cargo.toml --verbose

after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  gem install travis -v 1.8.8 --no-rdoc --no-ri &&
  travis login --org --no-interactive --github-token ${GH_TOKEN} &&
  travis restart --no-interactive -r slide-rs/specs-website

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cdff2f522a8c4588a82a
    on_success: always
    on_failure: always
    on_start: never
