language: rust
rust:
- nightly
- stable

cache:
  cargo: true
  apt: true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

branches:
  only:
    - staging
    - trying
    - master

before_script:
- which cargo-coveralls || cargo install cargo-travis
- export PATH="$PATH:$HOME/.cargo/bin"

script:
- cargo build --verbose
- cargo test --verbose
- cargo build --verbose --no-default-features
- cargo test --verbose --no-default-features
- cargo build --verbose --features serde
- cargo test --verbose --features serde
- cargo build --verbose --features rudy
- cargo test --verbose --features rudy
- cargo build --verbose --features common
- cargo test --verbose --features common
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo bench --verbose --no-run --all-features;
  fi
- cargo build --manifest-path ./specs-derive/Cargo.toml --verbose
- cargo test --manifest-path ./specs-derive/Cargo.toml --verbose

after_success: |
  if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
    cargo coveralls --exclude-pattern tests/;
  fi
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  gem install travis -v 1.8.8 --no-rdoc --no-ri &&
  travis login --org --no-interactive --github-token ${GH_TOKEN} &&
  travis restart --no-interactive -r slide-rs/specs-website

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cdff2f522a8c4588a82a
    on_success: always
    on_failure: always
    on_start: never
