[package]
name = "specs"
version = "0.4.0"
description = "SPECS Parallel ECS"
homepage = "https://github.com/slide-rs/specs"
repository = "https://github.com/slide-rs/specs"
keywords = ["gamedev"]
license = "Apache-2.0"
authors = ["slide-rs hackers"]

[dependencies]
mopa = "0.2"
pulse = "0.5"
threadpool = "1.0"
fnv = "1.0"
