[package]
name = "parsec"
version = "0.3.0"
description = "Parallel Systems for Entity Components"
homepage = "https://github.com/kvark/parsec"
repository = "https://github.com/kvark/parsec"
keywords = ["gamedev"]
license = "Apache-2.0"
authors = ["Dzmitry Malyshau", "Colin Sherratt"]

[dependencies]
mopa = "0.2"
pulse = "0.5"
threadpool = "1.0"
fnv = "1.0"
