# The URL the site will be built for
base_url = "https://slide-rs.github.io/"

title = "Specs Parallel ECS"
theme = "even"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = []

[extra]
even_title = "Specs Parallel ECS"

even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/docs", name = "Docs"},
    {url = "$BASE_URL/about", name = "About"},
]
